version: '3.8'

x-aws-cloudformation:
  Resources:
    NginxTCP443Listener:
      Properties:
        Certificates:
          - CertificateArn: 'arn:aws:acm:ap-south-1:135135176603:certificate/6e2d2b2f-bb4e-41c9-a799-069cef3805cc'
        Protocol: HTTPS
